### ISSUE TITLE
"LAN chip ... cause stability issues"

### ISSUE THREAD

**Issue by raszpl** [rodneyknaap/atx-286at-v1-mainboard#1]
>There is a LAN chip on the board but it should be left out, my tests were not great, it seems to cause stability issues in the system

I looked at your PCB and have some suggestions:

- reset (and COM1_CS/RTC_DS) is routed horizontally across the board on inner layer cutting ground plane in half right under Realtek and both CPLDs :o. Weak stitching top layer islands using sparse tiny high impedance(500nH if going top to bottom) Vias is not a good way of joining isolated grounds.

- only one Realtek VDD pin 17 is connected to power plane with thick via, rest are using tiny signal vias.

- one tht 100nF capacitor might not be enough to decouple Realtek, usually on ISA cards there are pairs of caps for every one of RTL8019 six VDD inputs. Personally I think 12 caps is total overkill, but there is some middle ground in between.

- Realtek differential TX output is routed along whole ISA J7 slot between pins, seemingly not a problem except it also goes between crystal pins (with interrupted ground, big no no) and over SD8-15 with no ground plane under. Once again ground plane is disrupted by signals being routed in it. This might lead to for example 20 MHz clock being coupled to upper part of data bus.

- looks like 1.8432M for UART also goes across whole board with no ground plane in places.

I highly suggest 7 part video series from Hans Rosenberg https://www.youtube.com/@HansRosenberg74/videos to get your head around good routing practices.

-----------------------------------------------------------------------------------------

>In GitHub there are separate projects published for each of my design iterations.

Would it be possible for you to upload whole kicad project (pcb, sch)? Much easier to browse and reason than gerbers re-imported into pcbnew.

- Whats the deal with RTC_CS from POWER_GOOD?
- Why additional redundant hex inverter generator for 32KHz?
- Power and reset generation seems very elaborate, 6 chips doing the work of two 7404 inverters and few RC pairs.

Am I correct in assuming those are leftovers from experimentation? Btw calling VBAT "VDD" was a funny trap, took me a good second to realize what was going on :)

If you ever plan adding DRAM or Cache Im happy to help. My hobby dabbling https://github.com/raszpl/FIC-486-GAC-2-Cache-Module https://github.com/raszpl/386RC-16

**Comment by rodneyknaap** [comment]
The realtek chip has been removed in the final PCB layout which will be published when finished. Builders are advised not to use any Realtek based ISA slot cards either.

**Comment by raszpl** [comment]
I read readme and most of vcfed thread. Obviously above comment was not means as a complaint about lack of ethernet :) but trying to point you at the source of your stability problems, things to keep in mind when routing to avoid signal integrity degradation.
